version: '3.7'

services:
  backend:
    container_name: django_shop
    tty: true
    build:
      context: .
      dockerfile: ./docker/project/Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver localhost:8000
    ports:
      - 8000:8000
#    expose:
#      - 8000
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - db
      - pgadmin

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres_shop
    volumes:
#     - ./docker/postgres/db:/var/lib/postgresql/data
     - ./docker/postgres/db:/tmp
      # - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_shop
    env_file:
      - .env.dev
    ports:
      - 15432:80
    volumes:
      - ./docker/postgres/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

# volumes:
#   pgdata: