version: '3.7'

services:
  backend:
    container_name: django_shop_dev
    tty: true
    build:
      context: .
      dockerfile: ./docker/project/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn Movies.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
#    expose:
#      - 8000
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres_shop_dev
    volumes:
     - ./docker/postgres/db:/var/lib/postgresql/data
      # - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_shop_dev
    env_file:
      - .env.dev
    ports:
      - 15432:80
    volumes:
      - ./docker/postgres/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

# volumes:
#   pgdata: